export const PERSONAS = {
  genz: {
    id: 'genz',
    name: 'YOLO Investor',
    emoji: '🔥',
    tagline: 'No cap, let\'s get this bag',
    description: 'Gen Z vibes, straight fire returns',
    color: '#f97316',
    gradient: 'from-orange-400 to-rose-500',
    accent: '#f97316',
    tone: {
      sipQ: 'Bestie, how much you dropping monthly? 💸',
      sipHint: 'Even ₹500 hits different long-term ngl',
      returnQ: 'What kinda returns are we cooking? 🍳',
      returnHint: 'Equity usually bussin at ~12%, lowkey',
      yearsQ: 'How long you holding fr fr? ⏰',
      yearsHint: 'Longer = more money, it\'s giving compound interest',
      resultTitle: 'Bestie, your bag:',
      insightPrefix: '🔥 Hot take:',
      goalQ: 'What\'s the vibe you\'re saving for?',
      noWayMsg: 'No cap, that\'s wild 🤯',
      achievable: '✅ Lowkey doable bestie, let\'s get it',
      tooHigh: '😅 That\'s a stretch... maybe step up the SIP fr',
    },
    featuredCalcs: ['sip', 'multiplier', 'compare'],
    theme: { primary: '#f97316', secondary: '#fb923c', bg: '#fff7ed', border: '#fed7aa' },
  },
  millennial: {
    id: 'millennial',
    name: 'Smart Hustler',
    emoji: '💼',
    tagline: 'Adulting with financial clarity',
    description: 'Practical, goal-driven, side-hustle energy',
    color: '#7c3aed',
    gradient: 'from-violet-500 to-purple-600',
    accent: '#7c3aed',
    tone: {
      sipQ: 'How much can you invest monthly?',
      sipHint: 'Automate it — pay yourself first',
      returnQ: 'Expected annual return?',
      returnHint: 'Diversified equity avg: 12%, debt: 7%',
      yearsQ: 'Investment horizon?',
      yearsHint: 'Longer horizon = more compounding power',
      resultTitle: 'Your financial picture:',
      insightPrefix: '💡 Smart move:',
      goalQ: 'What\'s your financial goal?',
      noWayMsg: 'That\'s impressive ROI! 🚀',
      achievable: '✅ Totally doable. Set up that SIP today.',
      tooHigh: '⚠️ Stretch goal — might need to increase income or push timeline',
    },
    featuredCalcs: ['sip', 'goal', 'stepup', 'retirement'],
    theme: { primary: '#7c3aed', secondary: '#8b5cf6', bg: '#f5f3ff', border: '#ddd6fe' },
  },
  fire: {
    id: 'fire',
    name: 'FIRE Chaser',
    emoji: '🏖️',
    tagline: 'Financial Independence, Retire Early',
    description: 'Optimization obsessed, retire at 40',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
    accent: '#10b981',
    tone: {
      sipQ: 'What\'s your monthly investment capacity?',
      sipHint: 'Every rupee invested = faster financial freedom',
      returnQ: 'Portfolio return assumption?',
      returnHint: 'FIRE portfolios typically target 8-12% real returns',
      yearsQ: 'Years to financial independence?',
      yearsHint: 'Lower this number. That\'s the game.',
      resultTitle: 'FIRE projection:',
      insightPrefix: '🎯 FIRE insight:',
      goalQ: 'Your FIRE number target?',
      noWayMsg: 'That\'s early retirement territory! 🏖️',
      achievable: '✅ On track for FIRE! Keep optimizing.',
      tooHigh: '📊 Optimize SWR and returns — adjust your FIRE timeline',
    },
    featuredCalcs: ['retirement', 'sip', 'compare', 'cagr'],
    theme: { primary: '#10b981', secondary: '#34d399', bg: '#ecfdf5', border: '#a7f3d0' },
  },
  conservative: {
    id: 'conservative',
    name: 'The Safe Bettor',
    emoji: '🛡️',
    tagline: 'Slow and steady builds wealth',
    description: 'FD, PPF, guaranteed returns focused',
    color: '#3b82f6',
    gradient: 'from-blue-500 to-cyan-500',
    accent: '#3b82f6',
    tone: {
      sipQ: 'How much would you like to save monthly?',
      sipHint: 'Consistent saving is the foundation of wealth',
      returnQ: 'Expected return rate?',
      returnHint: 'FD: 7%, PPF: 7.1%, RD: 6.5%',
      yearsQ: 'For how many years?',
      yearsHint: 'The longer you hold, the safer it gets',
      resultTitle: 'Your secure future:',
      insightPrefix: '🛡️ Safety note:',
      goalQ: 'What are you saving for?',
      noWayMsg: 'Great — conservative but meaningful growth!',
      achievable: '✅ Very achievable with disciplined saving',
      tooHigh: '📌 May take longer — consider adding equity exposure',
    },
    featuredCalcs: ['fd', 'ppf', 'emi', 'sip'],
    theme: { primary: '#3b82f6', secondary: '#60a5fa', bg: '#eff6ff', border: '#bfdbfe' },
  },
  pro: {
    id: 'pro',
    name: 'Power Analyst',
    emoji: '📊',
    tagline: 'Deep dive into every number',
    description: 'XIRR, CAGR, tax-adjusted, real returns',
    color: '#1e293b',
    gradient: 'from-slate-700 to-slate-900',
    accent: '#1e293b',
    tone: {
      sipQ: 'Monthly investment amount (pre-tax):',
      sipHint: 'Includes EPF, NPS, ELSS, and direct equity',
      returnQ: 'Pre-tax nominal return (%):',
      returnHint: 'Account for expense ratio, exit load, and taxes',
      yearsQ: 'Investment period (years):',
      yearsHint: 'Consider SWR for post-retirement drawdown phase',
      resultTitle: 'Pre/Post-tax analysis:',
      insightPrefix: '📊 Analysis:',
      goalQ: 'Target corpus (inflation-adjusted):',
      noWayMsg: 'Strong risk-adjusted return — verify with XIRR',
      achievable: '✅ Within expected parameters',
      tooHigh: '⚠️ Deviation from mean — stress-test with lower return scenarios',
    },
    featuredCalcs: ['xirr', 'cagr', 'tax', 'compare'],
    theme: { primary: '#1e293b', secondary: '#334155', bg: '#f8fafc', border: '#e2e8f0' },
  },
};

export const DEFAULT_PERSONA = 'millennial';
